# Generated by Django 4.2.2 on 2023-06-21 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_comment_content_comment_text_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='developer',
            new_name='user',
        ),
    ]
