# Generated by Django 4.2.2 on 2023-06-19 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_feed_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='developer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
