# Generated by Django 4.2.2 on 2023-06-22 01:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_feedcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
        migrations.AddField(
            model_name='feedcomment',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
    ]
